spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages
  redis:
    host: localhost
    port: 6379
    timeout: 5000




comment.avatar: /images/avatar.png