spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    data-username: root
    data-password: 1234
  jpa:
    hibernate:
      ddl-auto: none #update会根据类中的结构修改数据库中表的结构
    show-sql: true #在控制台输出sql语句
logging:
  level:
    root: warn
    com.yang: info
  file:
    name: log/blog-pro.log
server:
  port: 8081