spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: update #update会根据类中的结构修改数据库中表的结构
    show-sql: true #在控制台输出sql语句
logging:
  level:
    root: warn
    com.yang: info
  file:
    name: log/blog-pro.log
server:
  port: 8080